apiVersion: v1
kind: Pod
metadata:
  name: nginxpod2
  labels:
   env: whatsapp 
spec:
  nodeSelector:
     gpu: "true"
  containers:
  - name: nginxcon
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 80
