apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
spec:
  containers:
  - name: nginxcon
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
          - name: myconfigvolume
            mountPath: /ect/nginx/conf.d/
  volumes:
    - name: myconfigvolume
      configMap: 
           name: mynginxconf
