apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
spec:
  containers:
  - name: mysqlcon
    image: mysql
    ports:
     - containerPort: 3306
    env: 
     - name: MYSQL_ROOT_PASSWORD
       valueFrom: 
             secretKeyRef:
                   name: mysqlsecret
                   key: MYSQL_ROOT_PASSWORD

