apiVersion: apps/v1
kind: Deployment
metadata:
     name: myngpodrs
spec:
  replicas: 5
  selector:
      matchLabels:
        env: testing
  template:
    metadata:
       labels:
         env: testing
    spec:
     containers:
           - image: nginx
             name: ngcontainer
             ports:
                -  containerPort: 80
             volumeMounts:
                  - name: html
                    mountPath: /usr/share/nginx/html
     volumes:
       - name: html
         persistentVolumeClaim:
             claimName: mypvc  
             
