apiVersion: apps/v1
kind: Replicaset
metadata:
     name: myngpodrs
spec:
  replicas: 5
  selector:
      matchLabels:
        env: testing
  template:
    metadata:
       labels:
         env: testing
    spec:
     containers:
           - image: nginx
             name: ngcontainer
             ports:
                -  containerPort: 80
             livenessProbe:
                   httpGet:
                     path: /index.html
                     port: 80
                   initialDelaySeconds: 10
